env:
  APP_NAME: ${BUILDKITE_PIPELINE_SLUG}

steps:
- label: ":golangci-lint: lint :lint-roller:"
  key: "lint"
  plugins:
    - docker#v5.10.0:
        environment:
          - GOFLAGS=-buildvcs=false
        image: "registry.hub.docker.com/golangci/golangci-lint:v1.57-alpine"
        command: ["golangci-lint", "run", "-v", "--timeout", "5m"]

- label: ":test_tube: test"
  key: "test"
  plugins:
    - docker-compose#v4.16.0:
        cli-version: 2
        run: go
        config: docker-compose-ci.yml
        command: ["make", "test"]
